name: EpicRPGRotations
version: 2.0.0
main: me.Vark123.EpicRPGRotations.Main
author: Vark123
depend: [ChestCommands,MythicMobs,Vault,PlaceholderAPI,CalendarEvents,NBTAPI]
api-version: 1.18

commands:
  epicrpgrotate:
    aliases: [rpgrot, rpgrotation, erpgrot, erpgrotation, epicrpgrot, epirpgrotation]